import { beforeEach, describe, expect, it, vi } from 'vitest'
import { ref } from 'vue'
import { useCrudStore } from './useCrudStore'
import { EntrepreneurSchema } from '../schemas/entrepreneur'
import { useStorage } from '@/composables/useStorage'
import { z } from 'zod'

// Mock the useStorage composable
vi.mock('@/composables/useStorage')

const FILE_BUCKET = 'avatars'

// Create a mock DB object with the necessary methods
const createMockDb = () => {
  const mockData: Record<string, any> = {}
  return {
    entrepreneurs: {
      add: vi.fn(async (item: any) => {
        const id = item.id || crypto.randomUUID()
        mockData[id] = { ...item, id }
        return id
      }),
      get: vi.fn(async (id: string) => mockData[id]),
      put: vi.fn(async (item: any) => {
        mockData[item.id] = item
        return item.id
      }),
      delete: vi.fn(async (id: string) => {
        delete mockData[id]
        return 1
      }),
      bulkGet: vi.fn(async (ids: string[]) => ids.map((id) => mockData[id]).filter(Boolean)),
      bulkDelete: vi.fn(async (ids: string[]) => {
        ids.forEach((id) => delete mockData[id])
        return ids.length
      }),
      toArray: vi.fn(async () => Object.values(mockData))
    },
    avatars: {
      put: vi.fn(),
      get: vi.fn(),
      delete: vi.fn()
    }
  }
}

describe('useCrudStore', () => {
  let mockDb: any
  let mockUploadFile: any
  let mockUpdateFile: any
  let mockDeleteFile: any

  beforeEach(() => {
    mockDb = createMockDb()
    vi.clearAllMocks()

    // Mock useStorage return values
    mockUploadFile = vi.fn()
    mockUpdateFile = vi.fn()
    mockDeleteFile = vi.fn()
    vi.mocked(useStorage).mockReturnValue({
      loading: ref(false),
      error: ref(null),
      uploadFile: mockUploadFile,
      updateFile: mockUpdateFile,
      deleteFile: mockDeleteFile,
      getFileUrl: vi.fn()
    })

    vi.stubGlobal('crypto', {
      randomUUID: vi.fn(() => 'test-uuid-123')
    })
  })

  it('validates data against schema during add', async () => {
    const store = useCrudStore({
      schema: EntrepreneurSchema,
      tableName: 'entrepreneurs',
      db: mockDb
    })

    // Valid data should pass schema validation
    const validData = {
      firstName: 'John',
      lastName: 'Doe',
      slug: 'john-doe',
      contact: { email: 'john@example.com' }
    }

    await expect(store.add(validData)).resolves.not.toThrow()
    expect(mockDb.entrepreneurs.add).toHaveBeenCalled()
    expect(store.items.value).toHaveLength(1)

    // Invalid data should fail schema validation
    const invalidData = {
      firstName: 'John' // missing required lastName, slug, and contact
    }

    await expect(store.add(invalidData as any)).rejects.toThrow(z.ZodError)
    expect(mockDb.entrepreneurs.add).not.toHaveBeenCalledWith(
      expect.objectContaining(invalidData)
    )
    expect(store.items.value).toHaveLength(1) // Optimistic update should be reverted
  })

  it('validates data against schema during update', async () => {
    const store = useCrudStore({
      schema: EntrepreneurSchema,
      tableName: 'entrepreneurs',
      db: mockDb
    })

    // Add an initial item
    const initialData = {
      id: 'ent1',
      firstName: 'John',
      lastName: 'Doe',
      slug: 'john-doe',
      contact: { email: 'john@example.com' }
    }
    await mockDb.entrepreneurs.add(initialData)
    store.items.value = [initialData] // Manually set for optimistic update checks

    // Valid data with id should pass schema validation
    const validUpdateData = { ...initialData, firstName: 'Jane' }
    await expect(store.update(validUpdateData)).resolves.not.toThrow()
    expect(mockDb.entrepreneurs.put).toHaveBeenCalledWith(validUpdateData)
    expect(store.items.value[0]!.firstName).toBe('Jane')

    // Invalid data should fail schema validation
    const invalidUpdateData = { ...initialData, lastName: undefined }
    await expect(store.update(invalidUpdateData as any)).rejects.toThrow(z.ZodError)
    expect(mockDb.entrepreneurs.put).not.toHaveBeenCalledWith(
      expect.objectContaining(invalidUpdateData)
    )
    expect(store.items.value[0]!.firstName).toBe('Jane') // Should revert to previous valid state
  })

  it('handles avatar upload during add', async () => {
    const store = useCrudStore({
      schema: EntrepreneurSchema,
      tableName: 'entrepreneurs',
      db: mockDb
    })
    const mockFile = new File(['dummy content'], 'avatar.jpg', { type: 'image/jpeg' })
    mockUploadFile.mockResolvedValue('dexie://avatars/test-uuid-123/avatar.jpg')

    const dataWithFileAvatar = {
      firstName: 'John',
      lastName: 'Doe',
      slug: 'john-doe',
      contact: { email: 'john@example.com' },
      avatar: mockFile
    }

    const addedItem = await store.add(dataWithFileAvatar as any)

    expect(mockUploadFile).toHaveBeenCalledWith(
      mockFile,
      'test-uuid-123/avatar.jpg' // id will be generated by add function
    )
    expect(addedItem?.avatar).toBe('dexie://avatars/test-uuid-123/avatar.jpg')
    expect(mockDb.entrepreneurs.add).toHaveBeenCalledWith(
      expect.objectContaining({ avatar: 'dexie://avatars/test-uuid-123/avatar.jpg' })
    )
  })

  it('handles avatar update during update', async () => {
    const store = useCrudStore({
      schema: EntrepreneurSchema,
      tableName: 'entrepreneurs',
      db: mockDb
    })

    const initialItem = {
      id: 'ent1',
      firstName: 'John',
      lastName: 'Doe',
      slug: 'john-doe',
      contact: { email: 'john@example.com' },
      avatar: 'dexie://avatars/ent1/old-avatar.jpg'
    }
    await mockDb.entrepreneurs.add(initialItem)
    store.items.value = [initialItem]

    const newFile = new File(['new content'], 'new-avatar.png', { type: 'image/png' })
    mockUpdateFile.mockResolvedValue('dexie://avatars/ent1/new-avatar.png')

    const updatedItem = { ...initialItem, avatar: newFile }
    await store.update(updatedItem as any)

    expect(mockUpdateFile).toHaveBeenCalledWith(
      newFile,
      'ent1/new-avatar.png',
      'dexie://avatars/ent1/old-avatar.jpg'
    )
    expect(store.items.value[0]!.avatar).toBe('dexie://avatars/ent1/new-avatar.png')
    expect(mockDb.entrepreneurs.put).toHaveBeenCalledWith(
      expect.objectContaining({ avatar: 'dexie://avatars/ent1/new-avatar.png' })
    )
  })

  it('properly cleans up avatar files during remove', async () => {
    const store = useCrudStore({
      schema: EntrepreneurSchema,
      tableName: 'entrepreneurs',
      db: mockDb
    })

    const itemWithAvatar = {
      id: 'ent1',
      firstName: 'John',
      lastName: 'Doe',
      slug: 'john-doe',
      contact: { email: 'john@example.com' },
      avatar: 'dexie://avatars/ent1/avatar.jpg'
    }
    await mockDb.entrepreneurs.add(itemWithAvatar)
    store.items.value = [itemWithAvatar]

    await store.remove('ent1')

    expect(mockDeleteFile).toHaveBeenCalledWith('dexie://avatars/ent1/avatar.jpg')
    expect(mockDb.entrepreneurs.delete).toHaveBeenCalledWith('ent1')
    expect(store.items.value).toHaveLength(0)
  })

  it('properly cleans up avatar files during removeMany', async () => {
    const store = useCrudStore({
      schema: EntrepreneurSchema,
      tableName: 'entrepreneurs',
      db: mockDb
    })

    const item1 = {
      id: 'ent1',
      firstName: 'John',
      lastName: 'Doe',
      slug: 'john-doe',
      contact: { email: 'john@example.com' },
      avatar: 'dexie://avatars/ent1/avatar1.jpg'
    }
    const item2 = {
      id: 'ent2',
      firstName: 'Jane',
      lastName: 'Smith',
      slug: 'jane-smith',
      contact: { email: 'jane@example.com' },
      avatar: 'dexie://avatars/ent2/avatar2.jpg'
    }
    await mockDb.entrepreneurs.add(item1)
    await mockDb.entrepreneurs.add(item2)
    store.items.value = [item1, item2]

    await store.removeMany(['ent1', 'ent2'])

    expect(mockDeleteFile).toHaveBeenCalledWith('dexie://avatars/ent1/avatar1.jpg')
    expect(mockDeleteFile).toHaveBeenCalledWith('dexie://avatars/ent2/avatar2.jpg')
    expect(mockDb.entrepreneurs.bulkDelete).toHaveBeenCalledWith(['ent1', 'ent2'])
    expect(store.items.value).toHaveLength(0)
  })

  it('reverts optimistic updates on add error', async () => {
    const store = useCrudStore({
      schema: EntrepreneurSchema,
      tableName: 'entrepreneurs',
      db: mockDb
    })

    const validData = {
      firstName: 'John',
      lastName: 'Doe',
      slug: 'john-doe',
      contact: { email: 'john@example.com' }
    }

    mockDb.entrepreneurs.add.mockRejectedValueOnce(new Error('DB Error')) // Make add fail

    await expect(store.add(validData)).rejects.toThrow('DB Error')
    expect(store.items.value).toHaveLength(0) // Optimistic add should be reverted
  })

  it('reverts optimistic updates on update error', async () => {
    const store = useCrudStore({
      schema: EntrepreneurSchema,
      tableName: 'entrepreneurs',
      db: mockDb
    })

    const initialItem = {
      id: 'ent1',
      firstName: 'John',
      lastName: 'Doe',
      slug: 'john-doe',
      contact: { email: 'john@example.com' }
    }
    await mockDb.entrepreneurs.add(initialItem)
    store.items.value = [initialItem]

    const updateData = { ...initialItem, firstName: 'Jane' }
    mockDb.entrepreneurs.put.mockRejectedValueOnce(new Error('Update DB Error'))

    await expect(store.update(updateData)).rejects.toThrow('Update DB Error')
    expect(store.items.value[0]!.firstName).toBe('John') // Should revert to original
  })

  it('searches items correctly', () => {
    const store = useCrudStore({
      schema: EntrepreneurSchema,
      tableName: 'entrepreneurs',
      db: mockDb
    })

    const item1 = {
      id: 'test-id-1',
      firstName: 'John',
      lastName: 'Doe',
      slug: 'john-doe',
      contact: { email: 'john@example.com' }
    }

    const item2 = {
      id: 'test-id-2',
      firstName: 'Jane',
      lastName: 'Smith',
      slug: 'jane-smith',
      contact: { email: 'jane@example.com' }
    }

    store.items.value = [item1, item2]

    const results = store.search('john', ['firstName'], store.items)
    expect(results).toHaveLength(1)
    expect(results[0]!.firstName).toBe('John')

    const allResults = store.search('', ['firstName'], store.items)
    expect(allResults).toHaveLength(2)
  })

  it('handles errors consistently during fetchAll', async () => {
    const store = useCrudStore({
      schema: EntrepreneurSchema,
      tableName: 'entrepreneurs',
      db: mockDb
    })
    mockDb.entrepreneurs.toArray.mockRejectedValueOnce(new Error('FetchAll Error'))

    await expect(store.fetchAll()).rejects.toThrow('FetchAll Error')
    expect(store.error.value).toBe('FetchAll Error')
  })

  it('handles errors consistently during fetchOne', async () => {
    const store = useCrudStore({
      schema: EntrepreneurSchema,
      tableName: 'entrepreneurs',
      db: mockDb
    })
    mockDb.entrepreneurs.get.mockRejectedValueOnce(new Error('FetchOne Error'))

    await expect(store.fetchOne('some-id')).rejects.toThrow('FetchOne Error')
    expect(store.error.value).toBe('FetchOne Error')
  })
})